[project]
name = "gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ChingangbamDpakAngom", email = "cdeepakangom@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "uvicorn[standard]>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
